afpy/routes/home.py
import json

from docutils.core import publish_parts
from docutils.writers import html5_polyglot
from flask import abort
from flask import Blueprint
from flask import render_template
from flask import send_from_directory
from peewee import DoesNotExist

from afpy.models.JobPost import JobPost
from afpy.models.NewsEntry import NewsEntry
from afpy import config

home_bp = Blueprint("home", __name__)


@home_bp.route("/")
def home_page():
    all_news = NewsEntry.select().where(NewsEntry.state == "published").order_by(NewsEntry.dt_submitted.desc()).limit(4)
    return render_template("pages/index.html", body_id="index", posts=all_news)


@home_bp.route("/communaute")
def community_page():
    with open(f"{config.AFPY_ROOT}/afpy/data/data.json", "r") as handle:
        meetups = json.load(handle)["meetups"]
    return render_template("pages/communaute.html", body_id="communaute", meetups=meetups)


@home_bp.route("/adherer")
def adhere_page():
    return render_template("pages/adhesions.html", body_id="adhesions")


@home_bp.route("/irc")
def irc_page():
    return render_template("pages/irc.html", body_id="irc")


@home_bp.route("/docs/<name>")
def render_rest(name):
    try:
        with open(f"{config.AFPY_ROOT}/afpy/templates/rest/{name}.rst") as fd:
            parts = publish_parts(
                source=fd.read(), writer=html5_polyglot.Writer(), settings_overrides={"initial_header_level": 2}
            )
    except FileNotFoundError:
        abort(404)
    return render_template("pages/rst.html", body_id=name, html=parts["body"], title=parts["title"])


@home_bp.route("/status")
def status():
    return {
        "actualites": {
            "waiting": NewsEntry.select().where(NewsEntry.state == "waiting").count(),
        },
        "emplois": {
            "waiting": JobPost.select().where(JobPost.state == "waiting").count(),
        },
    }


@home_bp.route("/posts/<int:post_id>")
def post_render(post_id: int):
    try:
        post = NewsEntry.get_by_id(post_id)
    except DoesNotExist:
        abort(404)
    return render_template("pages/post.html", body_id="post", post=post, name=post.title)


@home_bp.route("/posts/page/<int:current_page>")
def posts_page(current_page: int = 1):
    total_pages = (NewsEntry.select().where(NewsEntry.state == "published").count() // config.NEWS_PER_PAGE) + 1
    posts = NewsEntry.select().where(NewsEntry.state == "published").paginate(current_page, config.NEWS_PER_PAGE)
    return render_template(
        "pages/posts.html",
        body_id="posts",
        posts=posts,
        title="Actualités",
        current_page=current_page,
        total_pages=total_pages,
    )


@home_bp.route("/post_image/<path:path>")
def get_image(path):
    return send_from_directory(config.IMAGES_PATH, path)

afpy/routes/jobs.py
from flask import abort
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from peewee import DoesNotExist
from werkzeug.utils import secure_filename

from afpy.forms.JobPost import JobPostForm
from afpy.models.JobPost import JobPost
from afpy import config


jobs_bp = Blueprint("jobs", __name__)


@jobs_bp.route("/emplois/<int:post_id>")
def jobs_render(post_id: int):
    try:
        job = JobPost.get_by_id(post_id)
    except DoesNotExist:
        abort(404)
    return render_template("pages/job.html", body_id="emplois", job=job, name=job.title)


@jobs_bp.route("/emplois")
@jobs_bp.route("/emplois/page/<int:current_page>")
def jobs_page(current_page: int = 1):
    total_pages = (JobPost.select().where(JobPost.state == "published").count() // config.NEWS_PER_PAGE) + 1
    jobs = (
        JobPost.select()
        .where(JobPost.state == "published")
        .order_by(JobPost.dt_submitted.desc())
        .paginate(current_page, config.NEWS_PER_PAGE)
    )
    return render_template(
        "pages/jobs.html",
        body_id="emplois",
        jobs=jobs,
        title="Offres d'emploi",
        current_page=current_page,
        total_pages=total_pages,
    )


@jobs_bp.route("/emplois/new", methods=["GET"])
def new_job():
    return render_template("pages/edit_job.html")

afpy/routes/posts.py
from flask import abort
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from peewee import DoesNotExist
from werkzeug.utils import secure_filename

from afpy.forms.NewsEntry import NewsEntryForm
from afpy.models.NewsEntry import NewsEntry
from afpy import config

posts_bp = Blueprint("posts", __name__)


@posts_bp.route("/actualites/<int:post_id>")
def post_render(post_id: int):
    try:
        post = NewsEntry.get_by_id(post_id)
    except DoesNotExist:
        abort(404)
    return render_template("pages/post.html", body_id="actualites", post=post, name=post.title)


@posts_bp.route("/actualites")
@posts_bp.route("/actualites/page/<int:current_page>")
def posts_page(current_page: int = 1):
    total_pages = (NewsEntry.select().where(NewsEntry.state == "published").count() // config.NEWS_PER_PAGE) + 1
    posts = (
        NewsEntry.select()
        .where(NewsEntry.state == "published")
        .order_by(NewsEntry.dt_submitted.desc())
        .paginate(current_page, config.NEWS_PER_PAGE)
    )
    return render_template(
        "pages/posts.html",
        body_id="actualites",
        posts=posts,
        title="Actualités",
        current_page=current_page,
        total_pages=total_pages,
    )


@posts_bp.route("/actualites/new", methods=["GET", "POST"])
def new_post():
    form = NewsEntryForm()
    if form.validate_on_submit():
        title = form.title.data
        summary = form.summary.data
        content = form.content.data
        author = form.author.data
        author_email = form.author_email.data

        new_post = NewsEntry.create(
            title=title, summary=summary, content=content, author=author, author_email=author_email
        )
        flash("Merci ! Votre article apparaîtra après validation par un des administrateurs.", "success")

        if form.image.data:
            extension = secure_filename(form.image.data.filename).split(".")[-1].lower()
            filename = f"emplois.{new_post.id}.{extension}"
            filepath = f"{config.IMAGES_PATH}/{filename}"
            request.files[form.image.name].save(filepath)
            new_post.image_path = filename
            new_post.save()
        return redirect(url_for("posts.posts_page", current_page=1))
    return render_template("pages/edit_post.html", form=form, post=None, body_id="edit-post")

afpy/templates/pages/adhesions.html
{% extends '_parts/base.jinja2' %}

{% block header %}
    <h1>Adhésions</h1>
{% endblock header %}

{% block main %}
    {% set helloasso_url = "https://www.helloasso.com/associations/afpy/adhesions/adhesion-2023-a-l-afpy" %}
    <h2>Adhérez à l'AFPy</h2>
    <iframe id="haWidget" src="{{ helloasso_url }}/widget"></iframe>
    <p>Si le widget ne fonctionne pas, essayez cette page : <a href="{{ helloasso_url }}">{{ helloasso_url }}</a></p>
{% endblock main %}

afpy/templates/pages/communaute.html
{% extends "_parts/base.jinja2" %}

{% block header %}
    <h1>Communauté</h1>
{% endblock header %}

{% block main %}
    <h2>Forum de discussion</h2>
    <p>
        Afin d'échanger avec la communauté, un forum de discussion est disponible et
        traite de tous les sujets autour de Python.
    </p>
    <p>
        <a href="https://discuss.afpy.org/">Forum</a>
    </p>

    <h2>Rencontres</h2>
    <p>
        Afin de partager autour du langage Python, de ses pratiques, de sa technique et de son écosystème,
        des évènements sont organisés régulièrement dans divers lieux.
    </p>
    <ul>
        {% for city, url in meetups.items() %}
            <li><a href="{{ url }}">{{ city | capitalize }}</a></li>
        {% endfor %}
    </ul>

    <h2>PyConFr</h2>
    <p>
        La PyConFr est un évènement organisé chaque année depuis 10+ ans par l'AFPy.
        Cette conférence est gratuite, entièrement organisée par des bénévoles et
        regroupe développeu·ses·rs, chercheu·ses·rs, étudiant·e·s et amat·rices·eurs
        autour d'une même passion pour le langage de programmation Python.
    </p>
    <p>
        <a href="https://www.pycon.fr/">PyConFr</a>
    </p>

    <h2>April</h2>
    <p>
        Pionnière du logiciel libre en France, l'April  est depuis 1996 un acteur majeur de la démocratisation
        et de la diffusion du logiciel libre et des standards ouverts auprès du grand public,
        des professionnels et des institutions dans l'espace francophone.
    </p>
    <p>
        <a href="http://april.org/campagne/">April</a>
    </p>
{% endblock main %}

afpy/templates/pages/discussion.html
{% extends "_parts/base.jinja2" %}

{% block header %}
    <h1>Discussion</h1>
{% endblock header %}

{% block main %}
    <p>Depuis cette page web vous pouvez</p>

    <ul>
        <li>venir discuter avec l'association sur le canal <a href="#tchatafpy">#afpy</a></li>
        <li>parler Python en français sur le canal <a href="#tchatpython">#python-fr</a></li>
        <li>accéder aux <a href="https://lists.afpy.org/mailman/listinfo/">Mailing Lists</a></li>
    </ul>

    <h2>Bon à savoir</h2>

    <p>
        IRC (Internet Relay Chat) permet d'utiliser plusieurs canaux de discussion en simultané. Si vous vous trouvez sur #afpy et souhaitez rejoindre #python-fr, rien de plus simple, tapez :
        <code>/join #python-fr</code>
    </p>

    <p>
        Si vous souhaitez changer de surnom après connexion :
        <code>/nick nouveaunom</code>
    </p>

    <h2 id="tchatafpy">Discuter avec l'AFPy (organisation de la communauté)</h2>

    <iframe src="https://web.libera.chat/#afpy"></iframe>

    <p>
        Vous pouvez aussi accéder au T'chat via un client IRC : <a href="irc://irc.freenode.net/afpy">irc://irc.freenode.net/afpy</a>.
        Nous stockons <a href="http://logs.afpy.org/">les archives IRC du canal #afpy</a>.
    </p>

    <h2 id="tchatpython">Discuter autour de Python</h2>

    <iframe src="https://web.libera.chat/#python-fr"></iframe>

    <p>
        Vous pouvez aussi accéder au T'chat via un client IRC : <a href="irc://irc.libera.chat/python-fr">irc://irc.libera.chat/python-fr</a>.
    </p>
{% endblock main %}

afpy/templates/pages/edit_job.html
{% extends '_parts/base.jinja2' %}

{% block header %}
    <h1>Création d'un job</h1>
{% endblock header %}

{% block main %}

    <article>
      <h2>Pour plus de visibilité, la job board de l'AFPy bouge ici : <a href="https://discuss.afpy.org/c/emplois/14">https://discuss.afpy.org/c/emplois</a> !</h2>
      <p>
        Pour créer une offre d'emploi là bas, deux solutions :<br/>
        <ul>
          <li>Envoyer un email à jobs at afpy point org, le titre de votre offre en sujet, le message de votre offre en corps de message, c'est tout.</li>
          <li>Publier l'offre directement <a href="https://discuss.afpy.org">sur le forum</a>, dans la catégorie « <a href="https://discuss.afpy.org/c/emplois/14">Offres d'emploi</a> » en cliquant sur le bouton « Créer un sujet »</li>
        </ul>
      </p>
      <h2>C'est quoi https://discuss.afpy.org?</h2>
      <p>
        C'est une instance de <a href="https://discourse.org">Discourse</a>, un forum <a href="https://github.com/discourse/discourse">open source</a> qu'on héberge en france chez <a href="https://www.gandi.net/fr">Gandi</a>.
      </p>
    </article>
{% endblock main %}

afpy/templates/pages/edit_post.html
{% extends '_parts/base.jinja2' %}

{% block header %}
    <h1>
        {% if post %}
            Modification d'un article
        {% else %}
            Création d'un article
        {% endif %}
    </h1>
{% endblock header %}

{% block main %}


    <article>
        <form method="POST" action="{{ url_for("posts.new_post") }}" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            {% for field, errors in form.errors.items() %}
                <div class="alert alert-error">
                    {{ form[field].label }}: {{ ', '.join(errors) }}
                </div>
            {% endfor %}
            <label>{{ form.title.label }}
                {{ form.title(size=40) }}
            </label>
            <label>{{ form.summary.label }}
                {{ form.summary(size=100) }}
            </label>
            <label>{{ form.image.label }}
                {{ form.image }}
            </label>
            <label>{{ form.author.label }}
                {{ form.author(size=20) }}
            </label>
            <label>{{ form.author_email.label }}
                {{ form.author_email(size=40) }}
            </label>
            <label>{{ form.content.label }}
                <div class="pagedown-row">
                    <div class="pagedown-column">
                        {{ form.content(only_input=True, rows=30) }}
                    </div>
                    <div class="pagedown-column" style="margin-left: 40px;">
                        Prévisualisation:
                        {{ form.content(only_preview=True) }}
                    </div>
                </div>
            </label>
            <input type="submit" name="submit" value="Enregistrer" />
        </form>
        <p>
            L'adresse e-mail n'est pas rendue publique, elle est uniquement
            utilisée par les modérateurs pour vous contacter si nécessaire.
        </p>
    </article>
{% endblock main %}

afpy/templates/pages/index.html
{% extends '_parts/base.jinja2' %}

{% block header %}
    <h1><abbr>AFPy</abbr> Association Francophone Python</h1>
{% endblock header %}

{% block main %}
    <h2>AFPy</h2>
    <p>L'AFPy promeut le langage Python que ce soit auprès d'un public averti ou débutant.</p>
    <p>Les projets de l'AFPy :
      <ul>
        <li>L'organisation annuelle de la <a href="https://pycon.fr">PyConFr</a>.</li>
        <li>La traduction de <a href="https://docs.python.org/fr">la documentation de Python en français</a> (Licence CC0).</li>
        <li>La création d'un outil d'apprentissage et d'enseignement de Python : <a href="https://hackinscience.org">HackInScience</a> (Licence MIT).</li>
        <li>L'organisation d'<a href="https://discuss.afpy.org/c/meetups/12">évènements locaux ou en ligne.</a></li>
      </ul>
    </p>

    <h2>Adhérer</h2>
    <p>Il est possible de soutenir les projets de l'AFPy
      <a href="{{ url_for('home.adhere_page') }}">en cotisant ou en effectuant un don</a>.
    </p>

    <h2>Actualités</h2>
    <section id="index-news">
        {% for post in posts %}
            <article>
                <h3>{{ post.title }}</h3>
                <time pubdate datetime="{{ post.dt_published }}">
                    {{ post.dt_published.strftime('%d/%m/%Y') }}
                </time>
                {% if post.image_path %}
                    <img src="{{ url_for('home.get_image', path=post.image_path) }}" alt="{{ post.title }}" />
                {% endif %}
                {{ post.summary | safe }}
                <p><a href="{{ post|slug_url }}">Lire la suite…</a></p>
            </article>
        {% endfor %}
    </section>
{% endblock main %}

afpy/templates/pages/irc.html
{% extends "_parts/base.jinja2" %}

{% block header %}
    <h1>IRC</h1>
{% endblock header %}

{% block main %}
    <p>Depuis cette page web vous pouvez</p>

    <ul>
        <li>venir discuter avec l'association sur le canal <a href="#tchatafpy">#afpy</a></li>
        <li>parler Python en français sur le canal <a href="#tchatpython">#python-fr</a></li>
    </ul>

    <h2>Bon à savoir</h2>

    <p>
        IRC (Internet Relay Chat) permet d'utiliser plusieurs canaux de discussion en simultané. Si vous vous trouvez sur #afpy et souhaitez rejoindre #python-fr, rien de plus simple, tapez :
        <code>/join #python-fr</code>
    </p>

    <p>
        Si vous souhaitez changer de surnom après connexion :
        <code>/nick nouveaunom</code>
    </p>

    <h2 id="tchatafpy">Discuter avec l'AFPy (organisation de la communauté)</h2>

    <iframe src="https://web.libera.chat/#afpy"></iframe>

    <p>
        Vous pouvez aussi accéder au T'chat via un client IRC : <a href="irc://irc.libera.chat/afpy">irc://irc.libera.chat/afpy</a>.
        Nous stockons <a href="http://logs.afpy.org/">les archives IRC du canal #afpy</a>.
    </p>

    <h2 id="tchatpython">Discuter autour de Python</h2>

    <iframe src="https://web.libera.chat/#python-fr"></iframe>

    <p>
        Vous pouvez aussi accéder au T'chat via un client IRC : <a href="irc://irc.libera.chat/python-fr">irc://irc.libera.chat/python-fr</a>.
    </p>
{% endblock main %}

afpy/templates/pages/job.html
{% extends '_parts/base.jinja2' %}

{% block header %}
    <h1>{{ job.title }}</h1>
{% endblock header %}

{% block main %}

    {% if preview %}
        <a href="{{ url_for("jobs_moderation.moderate_view") }}">Retour à l'interface d'administration</a>
        {#        <p><a class="btn btn-warning" href="http://127.0.0.1:5000/admin/jobpost/edit/?id={{ job.id }}" role="button">Edit</a></p>#}
    {% endif %}

    <article>
        {% if preview %}
            <time pubdate datetime="">
                Pas publié
            </time>
        {% else %}
            <time pubdate datetime="{{ job.dt_published }}">
                Posté le {{ job.dt_published.strftime('%d/%m/%Y') }} à {{ job.dt_published.strftime('%H:%M:%S') }}
            </time>
        {% endif %}
        <p>
            <em>
                {{ job.summary | safe if job.summary }}
            </em>
        </p>
        {% if job.image_path %}
            <img class="job" src="{{ url_for('home.get_image', path=job.image_path) }}" alt="{{ job.title }}" />
        {% endif %}
        {{ job.content | md2html | safe }}
        <aside>
            <h2>{{ job.company or "(Société inconnue)" }}</h2>
            <dl>
                <dt>Adresse</dt>
                <dd>{{ job.location }}</dd>
                <dt>Personne à contacter</dt>
                <dd>{{ job.contact_info }}</dd>
                {% if job.phone %}
                    <dt>Téléphone</dt>
                    <dd><a href="tel:{{ job.phone }}">{{ job.phone }}</a></dd>
                {% endif %}
                {% if job.email %}
                    <dt>Adresse e-mail</dt>
                    <dd><a href="mailto:{{ job.email }}">{{ job.email }}</a></dd>
                {% endif %}
            </dl>
        </aside>
    </article>
{% endblock main %}

afpy/templates/pages/jobs.html
{% extends '_parts/base.jinja2' %}

{% block header %}
    <h1>{{ title }}</h1>
{% endblock header %}

{% block main %}
    <aside>
      <h2>Pour plus de visibilité, la job board de l'AFPy bouge ici : <a href="https://discuss.afpy.org/c/emplois/14">https://discuss.afpy.org/c/emplois</a> !</h2>
      <p>
        Pour créer une offre d'emploi là bas, deux solutions :<br/>
        <ul>
          <li>Envoyer un email à jobs at afpy point org, le titre de votre offre en sujet, le message de votre offre en corps de message, c'est tout.</li>
          <li>Publier l'offre directement <a href="https://discuss.afpy.org">sur le forum</a>, dans la catégorie « <a href="https://discuss.afpy.org/c/emplois/14">Offres d'emploi</a> » en cliquant sur le bouton « Créer un sujet »</li>
        </ul>
      </p>
    </aside>
    {% for job in jobs %}
        <article>
            <h2>{{ job.title }}</h2>
            <time pubdate datetime="{{ job.dt_published }}">
                {{ job.dt_published.strftime('%d/%m/%Y') }}
            </time>
            {% if job.image_path %}
                <img src="{{ url_for('home.get_image', path=job.image_path) }}" alt="{{ job.title }}" />
            {% endif %}
            {% if job.summary %}{{ job.summary |safe }}{% else %}{{ job.content|truncate(50)|safe }}{% endif %}
            <p><a href="{{ job|slug_url }}">Lire la suite…</a></p>
        </article>
    {% endfor %}

    <aside>
        {% if current_page != 1 %}
            <a href="{{ url_for('jobs.jobs_page', current_page=(current_page - 1)) }}">Précedente</a>
        {% endif %}
        Page {{ current_page }}/{{ total_pages }}
        {% if current_page != total_pages %}
            <a href="{{ url_for('jobs.jobs_page', current_page=(current_page + 1)) }}">Suivante</a>
        {% endif %}
    </aside>
{% endblock main %}

afpy/templates/pages/post.html
{% extends '_parts/base.jinja2' %}

{% block header %}
    <h1>{{ post.title }}</h1>
{% endblock header %}

{% block main %}
    {% if preview %}
        <a href="{{ url_for("news_moderation.moderate_view") }}">Retour à l'interface d'administration</a>
        {#        <p><a class="btn btn-warning" href="http://127.0.0.1:5000/admin/jobpost/edit/?id={{ post.id }}" role="button">Edit</a></p>#}
    {% endif %}

    <article>
        {% if preview %}
            <time pubdate datetime="">
                Pas publié
            </time>
        {% else %}
            <time pubdate datetime="{{ post.dt_published }}">
                Posté le {{ post.dt_published.strftime('%d/%m/%Y') }} à {{ post.dt_published.strftime('%H:%M:%S') }}
            </time>
        {% endif %}
        <p>
            <em>
                {{ post.summary | safe if post.summary }}
            </em>
        </p>
        {% if post.image_path %}
            <img src="{{ url_for('home.get_image', path=post.image_path) }}" alt="{{ post.title }}" />
        {% endif %}
        {{ post.content | md2html | safe }}
    </article>
{% endblock main %}

afpy/templates/pages/posts.html
{% extends '_parts/base.jinja2' %}

{% block header %}
    <h1>{{ title }}</h1>
{% endblock header %}

{% block main %}
    <aside>
        Vous pouvez <a href="{{ url_for('posts.new_post') }}">créer un article</a> qui
        sera mis en ligne après acceptation de l'un des modérateurs.
    </aside>
    {% for post in posts %}
        <article>
            <h2>{{ post.title }}</h2>
            <time pubdate datetime="{{ post.dt_published }}">
                {{ post.dt_published.strftime('%d/%m/%Y') }}
            </time>
            {% if post.image_path %}
                <img src="{{ url_for('home.get_image', path=post.image_path) }}" alt="{{ post.title }}" />
            {% endif %}
            {{ post.summary | safe if post.summary }}
            <p><a href="{{ post|slug_url }}">Lire la suite…</a></p>
        </article>
    {% endfor %}

    <aside>
        {% if current_page != 1 %}
            <a href="{{ url_for('posts.posts_page', current_page=(current_page - 1)) }}">Précedente</a>
        {% endif %}
        Page {{ current_page }}/{{ total_pages }}
        {% if current_page != total_pages %}
            <a href="{{ url_for('posts.posts_page', current_page=(current_page + 1)) }}">Suivante</a>
        {% endif %}
    </aside>
{% endblock main %}

afpy/templates/pages/rst.html
{% extends '_parts/base.jinja2' %}

{% block header %}
    <h1>{{ title }}</h1>
{% endblock header %}

{% block main %}
    {{ html | safe }}
{% endblock main %}